services:
  db:
    image: postgres:16
    container_name: swush-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: swush
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d swush"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - "C:/selfhosted/swush/db:/var/lib/postgresql/data:rw"

    networks:
      - swush

  app:
    image: iconical/swush-ce:latest
    container_name: swush-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

    ports:
      - "3419:3000"
    volumes:
      # Can be removed if you don't want to persist uploads outside the container or using S3 for uploads
      - "D:/selfhosted/swush/uploads:/data/uploads:rw"
    networks:
      - swush

networks:
  swush:
