services:
  app:
    image: iconical/swush-ce:latest
    container_name: swush-app
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3419:3000"
    volumes:
      # Can be removed if you don't want to persist uploads outside the container or using S3 for uploads
      - D:/selfhosted/swush/uploads:/data/uploads:rw
    networks:
      - swush

networks:
  swush:
